### ISSUE TITLE
reword intro of sec 2

### ISSUE THREAD

**Issue by ivotron** [michaelsevilla/cudele-popper#19]
ivotron [6:30 PM] 
is the goal of section 2 to say that this is what you discovered, based on the analysis and breakdown of costs? (edited)

michaelsevilla [6:32 PM] 
I think the latter -- in our analysis we saw consistency/durability being a problem.

**Comment by michaelsevilla** [comment]
Addressed with 22cc49f0301065e615f777b0b35627316553f67e.
